#!/usr/bin/env python3
"""Strip or reject AI/vendor attribution in git and GitHub metadata.

Usage:
  strip-ai-git-attribution.py --commit-msg <file>
  strip-ai-git-attribution.py --check-pr
  strip-ai-git-attribution.py --self-test

The PR check reads title and body from the GitHub event, not from source files.
"""

from __future__ import annotations

import os
import re
import sys

VENDOR_RE = re.compile(
    r"paperclip|cursoragent|cursor\.com|noreply@paperclip|\bcursor\b|"
    r"\bclaude\b|anthropic|\bopenai\b|chatgpt|\bcopilot\b|\bgemini\b|"
    r"\bgrok\b|\bxai\b|codeium|windsurf|tabnine|\bdevin\b|\baider\b|"
    r"\bcody\b|sourcegraph|perplexity|\bmistral\b|continue\.dev|"
    r"amazon\s*q|github\s*copilot",
    re.IGNORECASE,
)
COAUTHOR_RE = re.compile(r"^\s*co-authored-by:\s*", re.IGNORECASE)
FOOTER_RE = re.compile(
    r"^\s*(?:made with|created with|generated by|generated with)\b",
    re.IGNORECASE,
)


def is_vendor_coauthor(line: str) -> bool:
    return bool(COAUTHOR_RE.match(line) and VENDOR_RE.search(line))


def is_attribution_footer(line: str) -> bool:
    return bool(FOOTER_RE.match(line))


def forbidden_reason(line: str) -> str | None:
    stripped = line.strip()
    if not stripped:
        return None
    if is_vendor_coauthor(stripped):
        return "vendor Co-authored-by"
    if is_attribution_footer(stripped):
        return "Made with / Created with / Generated by / Generated with footer"
    return None


def strip_message(text: str) -> str:
    kept: list[str] = []
    for line in text.splitlines():
        if forbidden_reason(line):
            continue
        kept.append(line.rstrip())
    while kept and kept[-1] == "":
        kept.pop()
    while kept and kept[0] == "":
        kept.pop(0)
    if not kept:
        return ""
    return "\n".join(kept) + "\n"


def find_forbidden_lines(text: str) -> list[str]:
    hits: list[str] = []
    for line in text.splitlines():
        reason = forbidden_reason(line)
        if reason:
            hits.append(f"{reason}: {line.strip()}")
    return hits


def fail(message: str, code: int = 1) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(code)


def run_commit_msg(path: str) -> None:
    original = open(path, encoding="utf-8").read()
    cleaned = strip_message(original)
    if not cleaned.strip():
        fail(
            "commit aborted: message was empty after removing AI/vendor attribution lines"
        )
    if cleaned != original:
        open(path, "w", encoding="utf-8", newline="\n").write(cleaned)


def run_check_pr() -> None:
    title = os.environ.get("PR_TITLE") or ""
    body = os.environ.get("PR_BODY") or ""
    hits = find_forbidden_lines(title) + find_forbidden_lines(body)
    if hits:
        fail(
            "PR title or body still attributes work to an AI, model, tool, or vendor:\n"
            + "\n".join(f"- {h}" for h in hits)
        )


def run_self_test() -> None:
    sample = (
        "Fix login timeout\n"
        "\n"
        "Co-authored-by: Luis Carbonell <luis@example.com>\n"
        "Co-Authored-By: Paperclip <noreply@paperclip.ing>\n"
        "Co-authored-by: Cursor Agent <cursoragent@cursor.com>\n"
        "Made with [Cursor](https://cursor.com)\n"
        "Generated by Claude\n"
        "Created with Copilot\n"
    )
    cleaned = strip_message(sample)
    assert "Luis Carbonell" in cleaned
    assert "Paperclip" not in cleaned
    assert "Cursor Agent" not in cleaned
    assert "Made with" not in cleaned
    assert "Generated by" not in cleaned
    assert "Created with" not in cleaned
    assert cleaned.startswith("Fix login timeout\n")

    empty = strip_message(
        "Co-Authored-By: Paperclip <noreply@paperclip.ing>\nMade with Cursor\n"
    )
    assert empty == ""

    hits = find_forbidden_lines("Made with Cursor\n")
    assert hits, hits
    clean_hits = find_forbidden_lines("Add retry for provider errors\n")
    assert clean_hits == []
    print("self-test ok")


def main(argv: list[str]) -> None:
    if len(argv) >= 2 and argv[1] == "--commit-msg":
        if len(argv) != 3:
            fail("usage: strip-ai-git-attribution.py --commit-msg <file>")
        run_commit_msg(argv[2])
        return
    if argv[1:] == ["--check-pr"]:
        run_check_pr()
        return
    if argv[1:] == ["--self-test"]:
        run_self_test()
        return
    fail(
        "usage: strip-ai-git-attribution.py --commit-msg <file> | --check-pr | --self-test"
    )


if __name__ == "__main__":
    main(sys.argv)
